fonttools/ufoLib2

- src/ufoLib2/glyphSet.py
- src/ufoLib2/plistlib.py
The new `ufoLib2.plistlib` is largely based on the builtin plistlib module but uses lxml to parse/write property list, instead of the expat parser and plistlib's pure-python xml writer.
The API is the same as the python3's plistlib, however only XML plist is supported for now (we don't care about binary plist).
Two additional functions fromtree/totree are exported, which are used for loading and dumping plist data that's embedded in GLIF XML tree:
- `fromtree` loads a plist from a previosly parsed element tree.
- `totree` does the reverse, and builds a new element tree from some plist-compatible data structure (dict, list, etc.).
About performaces, in my benchmarks this is about 10% faster (I was expecting more to be honest).
More gains could be achieved if we where to call into lxml C …
> rewrite plistlib to use lxml to parse/write

- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/layer.py
- src/ufoLib2/objects/layerSet.py
- src/ufoLib2/reader.py
follow the spec and set the default to the layer whose directory is named "glyphs" (the name of the layer can be user-defined, else it must be "public.default" -- though we don't validate that here yet).
Also:
- ~~added a new `getGlyphSets` method to the reader that returns an ordered dict of GlyphSets keyed by name;~~
- added `UFOReader.iterGlyphSets` method that returns an iterator over (layerName, GlyphSet) tuples
- ~~added a `defaultLayerName` property to LayerSet~~
- added `LayerSet.load` class constructor that takes a UFOReader instance and loads the layer set 
- added some backward-compatibility methods from the old ufoLib UFOReader api.
> don't enforce default layer to be first, etc.

- src/ufoLib2/objects/glyph.py
This seems to be a defcon-ism: https://github.com/robotools/defcon/blob/master/Lib/defcon/objects/glyph.py#L1104. fontMath depends on it: https://github.com/robotools/fontMath/blob/master/Lib/fontMath/mathGlyph.py#L316 (`_compressImage` returns `None` if no `fileName` is set).
> `Glyph.image = None` clears image

- src/ufoLib2/pointPens/glyphPointPen.py
fontMath's `FilterRedundantPointPen` does this: https://github.com/robotools/fontMath/blob/master/Lib/fontMath/mathGlyph.py#L486. The non-kwarg form of `identifier` in the functional call fails the call.
Not sure if this is a bug in fontMath? Any reason we want to have `**kwargs`?
> GlyphPointPen.addComponent: explicitly use identifier argument

- setup.py
requiring lxml is too heavy-handed, given that fonttools itself doesn't require and neither does defcon (which is similar to ufoLib2).
There still isn't a pre-compiled wheel for lxml for Python 3.8 on PyPI.
Better to keep it optional, i.e. 'pip install ufoLib2[lxml]'.
> make lxml optional

- src/ufoLib2/objects/glyph.py
- tests/conftest.py
- tests/objects/test_glyph.py
- tests/test_ufoLib2.py
defcon.Glyph has `copyDataFromGlyph`. It's convenient to have it here too, so clients can support both APIs (e.g. glyphsLib).
I also added `Glyph.copy` which returns a new copy rather than the one above which modifies the current object in-place. I recommend using this for ufoLib2-only client code.
> add methods to copy glyphs

- .coveragerc
- .pre-commit-config.yaml
- mypy.ini
- pyproject.toml
- setup.cfg
- setup.py
- src/ufoLib2/objects/__init__.py
- src/ufoLib2/objects/anchor.py
- src/ufoLib2/objects/component.py
- src/ufoLib2/objects/contour.py
- src/ufoLib2/objects/dataSet.py
- src/ufoLib2/objects/features.py
- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/guideline.py
- src/ufoLib2/objects/image.py
- src/ufoLib2/objects/imageSet.py
- src/ufoLib2/objects/info.py
- src/ufoLib2/objects/layer.py
- src/ufoLib2/objects/layerSet.py
- src/ufoLib2/objects/misc.py
- src/ufoLib2/objects/point.py
- src/ufoLib2/pointPens/glyphPointPen.py
- tests/test_ufoLib2.py
- pre-commit: Update deps, use `language: python_venv` everywhere to make it work with my Windows installation. pre-commit uses virtualenv by default otherwise.
- Turned on mypy's `disallow_incomplete_defs` option to increase strictness. Fixed all marked incomplete definitions.
- Removed some `object` subclassing that isn't necessary anymore in Python 3. Not sure how this got missed by the pyupgrade pre-commit hook.
- Port setup.py to the declarative setup.cfg format because I can.
- Add a Windows-specific lib installation dir so coverage comes out correct on Windows.
- Sort imports.
> Housekeeping

- src/ufoLib2/objects/info.py
Symmetric gridfit should be 2, and smoothing 3 per https://docs.microsoft.com/en-us/typography/opentype/spec/gasp
> Gasp settings enumerated incorrectly

- requirements.txt
- setup.cfg
- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/info.py
- src/ufoLib2/objects/layer.py
- src/ufoLib2/objects/layerSet.py
- src/ufoLib2/objects/misc.py
- tests/test_ufoLib2.py
Part of #41 to ease up projects wishing to support both defcon and ufoLib2
> support defcon-like Font(path) default constructor

- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/point.py
- tests/objects/test_glyph.py
#41 
I am sure there are more missing methods, but we can add them as we need.
> add Glyph.appendContour method for defcon API compat

- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/layer.py
- tests/objects/test_glyph.py
- tests/objects/test_layer.py
as @typemytype wrote in https://github.com/googlefonts/ufo2ft/issues/363#issuecomment-588356886
> Its maybe not a good plan to make the api between the ufoLib2 and defcon so different. According the spec a glyph name is not required, so on init of a glyph object the name should not be a requirement. But ufoLib2 makes it a required argument, I think this is wrong... and makes packages like ufo2ft complex where it should not be...
this PR makes Glyph.name default to None (e.g. for Glyphs without a parent layer).
As soon as a name-less glyph is added to a Layer object, it gets a name defined by its key in the layer underlying dict.
> make Glyph.name optional for compatibilty with defcon

- src/ufoLib2/objects/component.py
- src/ufoLib2/objects/contour.py
- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/misc.py
- tests/objects/test_component.py
- tests/objects/test_contour.py
- tests/objects/test_glyph.py
since we added for Glyph, we should also add the same methods for other two "drawable" objects, Contour and Component.
> also add getBounds and getControlBounds for Contour and Component classes

- src/ufoLib2/objects/dataSet.py
- src/ufoLib2/objects/imageSet.py
- src/ufoLib2/objects/misc.py
- tests/objects/test_datastore.py
1. Use abstract methods for reading and writing contents.
2. Images can't be put into subdirectories.
> Refactor DataStore and (Image|Data)Set

- src/ufoLib2/objects/component.py
- src/ufoLib2/objects/contour.py
- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/layer.py
- src/ufoLib2/objects/misc.py
- tests/objects/test_font.py
For compatibility with defcon.
> Add bounds/controlPointBounds properties

- .github/workflows/test.yml
Cramming everything into one step ignores tox failures?!
Also, test with minimum supported Python version and latest
> CI: Break up build steps

- docs/source/conf.py
- pyproject.toml
- src/ufoLib2/constants.py
- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/layer.py
- src/ufoLib2/objects/misc.py
- src/ufoLib2/typing.py
- tests/objects/test_object_lib.py
- tox.ini
The current iteration of this PR adds `object_lib(obj)` methods to `Font` and `Glyph`, where `obj` is the object you want to get the lib of (anchor, guideline, ...). If the object does not have an identifier yet, it gets assigned one.
This is simpler than changing the objects to carry their own lib, but also means that the lib of an object is not free-floating but really tied to the containing `Font` or `Glyph` object. This reflects how the data is serialized. UFO v4 may change this, we then change the API.
> Add public.objectLibs handling

- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/glyph.py
- tests/objects/test_object_lib.py
CamelCase is the prevailing casing sadly. Missed this the first time around.
> Rename object_lib to objectLib

- src/ufoLib2/objects/component.py
- src/ufoLib2/objects/contour.py
- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/layer.py
- src/ufoLib2/objects/misc.py
- src/ufoLib2/typing.py
More elegant than referring to Layer and Glyph explicitly, which nicely avoids circular imports.
Closes https://github.com/fonttools/ufoLib2/issues/110.
> Add GlyphSet protocol

- setup.cfg
Fixes #156
When using setuptools (commonly still used for distro packages because no other solution supports installing to bare packaging directory yet) to build a project it is not necessary or desired to have *wheel* in the loop. It is needed for releasing the project upstream of course, but not for installing it locally.
> Do not require wheel for all setuptools operations

- src/ufoLib2/objects/font.py
They clog up pytest's assert display and contribute no semantics to a Font.
Note that the custom `Font.__eq__` method already takes care not to use these fields for equality testing, but this is more about the fields showing up in pytest's custom assert failure report for `assert font1 == font2` where they serve no purpose.
> Don't compare private Font attributes

- src/ufoLib2/objects/font.py
- tests/test_ufoLib2.py
This is to continue supporting `font.kerning = {(a, b): -10, ...}` even after we typed Font.kerning as `Kerning` dict subclass (to customize (un)structuring via cattrs in #181).
Alternative to #188
> add property setter for Font.kerning to coerce dict to Kerning class

- src/ufoLib2/converters.py
- tests/test_converters.py
Instead of exposing a `ufoLib2.converters.default_converter` and call `unstructure` and `structure` methods on it, I like it better to define two global `structure` and `unstructure` functions (which are actually bound methods of the default converter re-exported as standalone functions), similarly to how one does`from cattr import structure, unstructure`.
E.g.: instead of `from ufoLib2.converters import default_converter as conv; conv.structure(..., Font)`, you now do
```python
import orjson
from ufoLib2.objects import Font
from ufoLib2.converters import structure, unstructure
with open("MyFont.json", "rb") as f:
json_data = orjson.loads(f.read())
font = structure(json_data, Font)
...
json_data = orjson.dumps(unstructure(font), option=orjson.OPT_INDENT_2 | orjson.OPT_SORT_KEYS)
with …
```
> export structure/unstructure public methods using default_converter

- src/ufoLib2/objects/font.py
- src/ufoLib2/objects/glyph.py
- src/ufoLib2/objects/layer.py
- src/ufoLib2/objects/lib.py
- tests/objects/test_font.py
- tests/test_converters.py
This adds the equivalent of defcon's tempLib to the Font, Layer and Glyph objects. It's a temporary 'lib' that does not get saved to disk. Can be useful at times (I need this in fontmake right now).
https://github.com/robotools/defcon/pull/367
> add tempLib to Font, Layer and Glyph (like defcon's)

- src/ufoLib2/objects/glyph.py
This is in line with what `ufoLib` does.
Fixes https://github.com/fonttools/fonttools/issues/3694
> [glyph] Add outputImpliedClosingLine to draw()

- src/ufoLib2/objects/info/__init__.py
This snuck through for a while! Not causing any problems, but noticed when debugging and thought it deserved a fix.
[A GitHub-wide search of the constant's name only shows this repository and forks thereof](https://github.com/search?q=%22EXTRA_CONDESED%22&type=code), and so we can be reasonably confident that this won't cause problems downstream.
> Fix typo in width class label

- src/ufoLib2/objects/font.py
Follow-up to #393.
Sadly only available in Python >= 3.10, but oh well.
> Ignore temporary directory cleanup errors
